# Generated by Django 5.0.6 on 2024-05-27 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare_app', '0003_alter_doctor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
    ]
